export type Product = {
  id: string;
  name: string;
  category: string;
  description: string;
  color: string;
  colorName: string;
  thickness: string;
  width: string;
  length: string;
  price: number;
  caseCount: number;
  casePrice: number;
  features: string[];
  featured: boolean;
};

export const products: Product[] = [
  // 30mm 識別テープ（0.08mm × 30mm × 50m）
  {
    id: "30mm-pink",
    name: "識別テープ 30mm ピンク",
    category: "30mm 識別テープ",
    description: "森林調査・測量の現場で最も使用頻度の高いピンク色の識別テープ。樹木への巻付けや枝への結束で遠方からの視認性に優れ、伐採予定木の目印や踏査ルートのマーキングに最適です。",
    color: "#FF69B4",
    colorName: "ピンク",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["高視認性", "文字書込み可", "非粘着"],
    featured: true,
  },
  {
    id: "30mm-red",
    name: "識別テープ 30mm 赤",
    category: "30mm 識別テープ",
    description: "伐採木・危険木のマーキングに広く使われる赤色テープ。鮮やかな発色で林内でも目立ちやすく、境界杭の目印や土木現場での区域表示にも活用されています。",
    color: "#DC143C",
    colorName: "赤",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["高視認性", "文字書込み可", "非粘着"],
    featured: true,
  },
  {
    id: "30mm-orange",
    name: "識別テープ 30mm 橙",
    category: "30mm 識別テープ",
    description: "境界線表示や間伐対象木のマーキングに使用される橙色テープ。緑の多い林内で赤と並んで視認性が高く、森林計画調査や造林作業の現場で重宝されます。",
    color: "#FF8C00",
    colorName: "橙",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["高視認性", "文字書込み可", "非粘着"],
    featured: false,
  },
  {
    id: "30mm-yellow",
    name: "識別テープ 30mm 黄",
    category: "30mm 識別テープ",
    description: "注意喚起や品種識別に活用される黄色テープ。林班境界の表示、植栽品種の色分け管理など幅広い用途で使用されています。油性ペンでの書込みも鮮明に読み取れます。",
    color: "#FFD700",
    colorName: "黄",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["高視認性", "文字書込み可", "非粘着"],
    featured: true,
  },
  {
    id: "30mm-green",
    name: "識別テープ 30mm 緑",
    category: "30mm 識別テープ",
    description: "残存木・保護木のマーキングに使われる緑色テープ。伐採しない木の目印や保全区域の境界表示に。他の色との組み合わせで複数の情報を色分け管理できます。",
    color: "#228B22",
    colorName: "緑",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["文字書込み可", "非粘着", "色分け管理"],
    featured: false,
  },
  {
    id: "30mm-blue",
    name: "識別テープ 30mm 青",
    category: "30mm 識別テープ",
    description: "測量ポイントや水源周辺のマーキングに活用される青色テープ。登山道の目印やトレイルマーキングにも人気が高く、山岳地帯での使用実績も豊富です。",
    color: "#1E90FF",
    colorName: "青",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["高視認性", "文字書込み可", "非粘着"],
    featured: false,
  },
  {
    id: "30mm-white",
    name: "識別テープ 30mm 白",
    category: "30mm 識別テープ",
    description: "文字の書込みに最適な白色テープ。番号・記号・日付などの記入がしやすく、樹木ナンバリングや調査記録の現場で活躍します。片面光沢仕上げで耐水性も確保。",
    color: "#FFFFFF",
    colorName: "白",
    thickness: "0.08mm",
    width: "30mm",
    length: "50m",
    price: 405,
    caseCount: 10,
    casePrice: 4050,
    features: ["文字書込み最適", "片面光沢", "非粘着"],
    featured: false,
  },
  // 15mm 識別テープ（0.08mm × 15mm × 50m）
  {
    id: "15mm-pink",
    name: "識別テープ 15mm ピンク",
    category: "15mm 識別テープ",
    description: "細幅で取り回しやすいピンク色の目印テープ。枝や杭への結束が簡単で、踏査ルートのマーキングや登山道の目印に最適。携帯性に優れたコンパクトサイズです。",
    color: "#FF69B4",
    colorName: "ピンク",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "結束しやすい", "非粘着"],
    featured: true,
  },
  {
    id: "15mm-red",
    name: "識別テープ 15mm 赤",
    category: "15mm 識別テープ",
    description: "伐採木や注意箇所の目印に使われる赤色の細幅テープ。軽量で携帯しやすく、山林踏査やトレイルランニングのコースマーキングにも活用されています。",
    color: "#DC143C",
    colorName: "赤",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "高視認性", "非粘着"],
    featured: false,
  },
  {
    id: "15mm-orange",
    name: "識別テープ 15mm 橙",
    category: "15mm 識別テープ",
    description: "林内での目印用に適した橙色の細幅テープ。15mm幅は目印専用として最適なサイズで、枝に結んでも風で目立ちやすく、測量や境界確認の現場で重宝されます。",
    color: "#FF8C00",
    colorName: "橙",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "結束しやすい", "非粘着"],
    featured: false,
  },
  {
    id: "15mm-yellow",
    name: "識別テープ 15mm 黄",
    category: "15mm 識別テープ",
    description: "注意表示や品種識別に使いやすい黄色の細幅テープ。コンパクトなので作業着のポケットに入れて持ち歩け、必要な時にすぐ使える利便性が魅力です。",
    color: "#FFD700",
    colorName: "黄",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "高視認性", "非粘着"],
    featured: false,
  },
  {
    id: "15mm-green",
    name: "識別テープ 15mm 緑",
    category: "15mm 識別テープ",
    description: "保護木や残存木の目印に使用される緑色の細幅テープ。色分け管理の一環として他の色と組み合わせて使用されることが多く、現場での情報整理に役立ちます。",
    color: "#228B22",
    colorName: "緑",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "色分け管理", "非粘着"],
    featured: false,
  },
  {
    id: "15mm-blue",
    name: "識別テープ 15mm 青",
    category: "15mm 識別テープ",
    description: "測量ポイントや登山ルートの目印に使用される青色の細幅テープ。登山・トレッキングでのルートマーキングに人気で、携帯しやすいサイズが好評です。",
    color: "#1E90FF",
    colorName: "青",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "高視認性", "非粘着"],
    featured: false,
  },
  {
    id: "15mm-white",
    name: "識別テープ 15mm 白",
    category: "15mm 識別テープ",
    description: "細幅ながら文字記入も可能な白色テープ。番号や記号を書き込んで個体識別に使えます。目印テープとしての携帯性と記録用途の両方を兼ね備えた製品です。",
    color: "#FFFFFF",
    colorName: "白",
    thickness: "0.08mm",
    width: "15mm",
    length: "50m",
    price: 238,
    caseCount: 20,
    casePrice: 4755,
    features: ["コンパクト", "文字書込み可", "非粘着"],
    featured: false,
  },
  // 寒冷地向け厚手テープ（0.10mm × 30mm × 100m）
  {
    id: "thick-30mm-pink",
    name: "厚手識別テープ 30mm ピンク",
    category: "厚手・特殊テープ",
    description: "寒冷地での使用を想定した厚手仕様（0.10mm）の識別テープ。通常品より厚みがあるため低温環境でも割れにくく、北海道・東北の冬季林業現場で高い評価を得ています。100mの長尺仕様。",
    color: "#FF69B4",
    colorName: "ピンク",
    thickness: "0.10mm",
    width: "30mm",
    length: "100m",
    price: 1184,
    caseCount: 10,
    casePrice: 11839,
    features: ["寒冷地対応", "厚手0.10mm", "長尺100m"],
    featured: true,
  },
  {
    id: "thick-30mm-blue",
    name: "厚手識別テープ 30mm 青",
    category: "厚手・特殊テープ",
    description: "寒冷地向け厚手仕様の青色テープ。0.10mmの厚みで耐久性が高く、長期間の屋外設置にも対応。冬季の森林調査や積雪地帯での境界マーキングに適しています。100m巻き。",
    color: "#1E90FF",
    colorName: "青",
    thickness: "0.10mm",
    width: "30mm",
    length: "100m",
    price: 1184,
    caseCount: 10,
    casePrice: 11839,
    features: ["寒冷地対応", "厚手0.10mm", "長尺100m"],
    featured: false,
  },
  // バイオ分解テープ（30mm × 100m）
  {
    id: "bio-30mm-red",
    name: "バイオ分解テープ 30mm 赤",
    category: "厚手・特殊テープ",
    description: "植物由来原料30%配合のバイオマス素材を使用した環境配慮型テープ。使用後は自然分解されるため、回収が困難な山林奥地でのマーキングに最適。環境負荷を低減しながら確実な識別を実現します。",
    color: "#DC143C",
    colorName: "赤",
    thickness: "0.08mm",
    width: "30mm",
    length: "100m",
    price: 550,
    caseCount: 10,
    casePrice: 5500,
    features: ["バイオマス素材", "自然分解", "長尺100m"],
    featured: true,
  },
  {
    id: "bio-30mm-pink",
    name: "バイオ分解テープ 30mm ピンク",
    category: "厚手・特殊テープ",
    description: "環境にやさしいバイオ分解性素材の識別テープ。100%生分解性樹脂を使用し、時間経過とともに自然に分解。FSC認証林や環境配慮型の森林施業現場で採用が広がっています。",
    color: "#FF69B4",
    colorName: "ピンク",
    thickness: "0.08mm",
    width: "30mm",
    length: "100m",
    price: 550,
    caseCount: 10,
    casePrice: 5500,
    features: ["バイオマス素材", "自然分解", "長尺100m"],
    featured: false,
  },
];

export const categories = ["すべて", "30mm 識別テープ", "15mm 識別テープ", "厚手・特殊テープ"];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}
